---

- hosts: mysql-servers
  tasks:
    - name: Ensure MySQL Python libraries are installed
      apt: name=python-mysqldb state=installed
           update_cache=yes cache_valid_time=86400

- hosts: mysql-master-a
  roles:
    - role: mysql
    - role: keepalived

- hosts: mysql-master-b
  roles:
    - role: mysql
    - role: keepalived

- hosts: mysql-slave-a
  roles:
    - role: mysql

- hosts: mysql-servers
  roles:
    - role: mysql-replication