---

- hosts: mysql-servers
  tasks:
    - name: Ensure MySQL Python libraries are installed
      apt: name=python-mysqldb state=installed
           update_cache=yes cache_valid_time=86400

- hosts: mysql-master-a
  roles:

    - role: mysql
      mysql_replication_role: master-master
      mysql_replication_master: mysql-master-b
      mysql_root_password: superpassword
      mysql_replication_user:
        name: replicator
        password: test
      mysql_cfg_override: |
        [mysqld]
        server-id = 1
        auto_increment_offset = 1
        auto_increment_increment = 2
        replicate-ignore-db = mysql
        binlog-ignore-db = mysql
        log-slave-updates
        tmpdir = /var/tmp
        log_bin = /var/log/mysql/mysql-bin.log
        bind-address = 0.0.0.0

    - role: keepalived
      keepalived_vrrp_scripts:
        healthcheck:
          script: healthcheck
          interval: 5
      keepalived_vrrp_instances:
        VI_1:
          interface: eth0
          state: SLAVE
          priority: 101
          smtp_alert: true
          authentication:
            auth_type: PASS
            auth_pass: ChangeME
          virtual_ipaddresses:
            - 192.168.255.201
          track_scripts:
            - healthcheck

- hosts: mysql-master-b
  roles:

    - role: mysql
      mysql_replication_role: master-master
      mysql_replication_master: mysql-master-a
      mysql_root_password: superpassword
      mysql_replication_user:
        name: replicator
        password: test
      mysql_cfg_override: |
        [mysqld]
        server-id = 2
        auto_increment_offset = 2
        auto_increment_increment = 2
        replicate-ignore-db = mysql
        binlog-ignore-db = mysql
        log-slave-updates
        tmpdir = /var/tmp
        log_bin = /var/log/mysql/mysql-bin.log
        bind-address = 0.0.0.0

    - role: keepalived
      keepalived_vrrp_scripts:
        healthcheck:
          script: healthcheck
          interval: 5
      keepalived_vrrp_instances:
        VI_1:
          interface: eth0
          state: BACKUP
          priority: 100
          smtp_alert: true
          nopreempt: true
          authentication:
            auth_type: PASS
            auth_pass: ChangeME
          virtual_ipaddresses:
            - 192.168.255.201
          track_scripts:
            - healthcheck

- hosts: mysql-slave-a
  roles:
    - role: mysql
      mysql_replication_role: slave
      mysql_replication_master: mysql-master-b
      mysql_root_password: superpassword
      mysql_replication_user:
        name: replicator
        password: "test"
      mysql_cfg_override: |
        [mysqld]
        server-id = 3
        read-only = 1
        tmpdir = /var/tmp

- hosts: mysql-servers
  roles:
    - role: mysql-replication
