---

- hosts: mysql-servers
  tasks:
  - name: Ensure MySQL Python libraries are installed
    apt: name=python-mysqldb state=installed update_cache=yes

- hosts: mysql-master-a
  roles:
    - role: mysql
      tags: master
      mysql_replication_role: master-master
      mysql_replication_master: mysql-master-b
      mysql_server_id: 1
      mysql_root_password_update: no
      mysql_root_password: superpassword
      mysql_bind_address: '{{ ansible_eth0.ipv4.address }}'
      mysql_replication_user:
        name: replicator
        host: "%"
        password: "test"
        priv: "*.*:REPLICATION SLAVE"
    - role: keepalived
      tags:
        - master
        - slave
      keepalived_vrrp_scripts:
        healthcheck:
          script: healthcheck
          interval: 5
      keepalived_vrrp_instances:
        VI_1:
          interface: eth0
          state: MASTER
          priority: 101
          smtp_alert: true
          authentication:
            auth_type: PASS
            auth_pass: 'ChangeME'
          virtual_ipaddresses:
            - 192.168.255.201
          track_scripts:
            - healthcheck

- hosts: mysql-master-b
  roles:
    - role: mysql
      tags: master
      mysql_replication_role: master-master
      mysql_replication_master: mysql-master-a
      mysql_server_id: 2
      mysql_root_password_update: no
      mysql_root_password: superpassword
      mysql_bind_address: '{{ ansible_eth0.ipv4.address }}'
      mysql_replication_user:
        name: replicator
        host: "%"
        password: "test"
        priv: "*.*:REPLICATION SLAVE"
    - role: keepalived
      tags:
        - master
        - slave
      keepalived_vrrp_scripts:
        healthcheck:
          script: healthcheck
          interval: 5
      keepalived_vrrp_instances:
        VI_1:
          interface: eth0
          state: BACKUP
          priority: 100
          smtp_alert: true
          nopreempt: true
          authentication:
            auth_type: PASS
            auth_pass: 'ChangeME'
          virtual_ipaddresses:
            - 192.168.255.201
          track_scripts:
            - healthcheck

- hosts: mysql-slave-a
  roles:
    - role: mysql
      tags: slave
      mysql_root_password_update: no
      mysql_root_password: superpassword
      mysql_replication_role: slave
      mysql_replication_master: mysql-master-a
      mysql_server_id: 3
      mysql_replication_user:
        name: replicator
        password: "test"
