---

- hosts: mysql-master-a
  vars_files:
    - vars/main.yml
    - vars/masterA.yml
  roles:
    - role: keepalived
      tags:
        - master
        - slave
      keepalived_vrrp_scripts:
        healthcheck:
          script: healthcheck
          interval: 5
      keepalived_vrrp_instances:
        VI_1:
          interface: eth0
          state: MASTER
          priority: 101
          smtp_alert: true
          authentication:
            auth_type: PASS
            auth_pass: 'ChangeME'
          virtual_ipaddresses:
            - 192.168.255.201
          track_scripts:
            - healthcheck
    - role: mysql
      tags: master

- hosts: mysql-master-b
  vars_files:
    - vars/main.yml
    - vars/masterB.yml
  roles:
    - role: keepalived
      tags:
        - master
        - slave
      keepalived_vrrp_scripts:
        healthcheck:
          script: healthcheck
          interval: 5
      keepalived_vrrp_instances:
        VI_1:
          interface: eth0
          state: BACKUP
          priority: 100
          smtp_alert: true
          nopreempt: true
          authentication:
            auth_type: PASS
            auth_pass: 'ChangeME'
          virtual_ipaddresses:
            - 192.168.255.201
          track_scripts:
            - healthcheck
    - role: mysql
      tags: master

- hosts: mysql-slaves
  vars_files:
    - vars/slave.yml
  roles:
    - role: mysql
      tags: slave
