# MasterA et B
- hosts: mysql-master-a
  vars_files:
    - vars/main.yml
    - vars/masterA.yml
  roles:
    - role: ansible-role-mysql
      tags: master

- hosts: mysql-master-b
  vars_files:
    - vars/main.yml
    - vars/masterB.yml
  roles:
    - role: ansible-role-mysql
      tags: master

# Slave
- hosts: mysql-slaves
  vars_files:
    - vars/slave.yml
  roles:
    - role: ansible-role-mysql
      tags: slave
