---

- name: Get OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"

- name: Check if MySQL is already installed
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL packages are installed
  apt: name={{ mysql_pkg }} state=installed
  register: deb_mysql_install_packages

- name: Ensure MySQL is stopped after initial install
  service: name=mysql state=stopped
  when: mysql_installed.stat.exists == false

- name: Delete innodb log files created by apt package after initial install
  shell: "rm -f {{ mysql_datadir }}/ib_logfile[01]"
  when: mysql_installed.stat.exists == false

- name: Check if MySQL packages were installed
  set_fact:
    mysql_install_packages: "{{ (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed) }}"

- include: configure.yml
- include: secure-installation.yml
#- include: replication.yml
