mysql_replication_role: slave
mysql_replication_master: mysql-master-b
mysql_root_password: superpassword
mysql_replication_user:
  name: replicator
  password: "test"
mysql_cfg_override: |
  [mysqld]
  server-id = 3
  read-only = 1
  tmpdir = /var/tmp